# /* wallust template - colors-hyprland */ 

$background = rgb(202121)
$foreground = rgb(E9E3D9)
$color0 = rgb(464747)
$color1 = rgb(4C473F)
$color2 = rgb(524A44)
$color3 = rgb(88475A)
$color4 = rgb(7A6F5F)
$color5 = rgb(627D6B)
$color6 = rgb(90836F)
$color7 = rgb(D7CEC1)
$color8 = rgb(979087)
$color9 = rgb(665F54)
$color10 = rgb(6D635B)
$color11 = rgb(B55F78)
$color12 = rgb(A2947E)
$color13 = rgb(82A78F)
$color14 = rgb(C1AF93)
$color15 = rgb(D7CEC1)
