
# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

windowrule = opacity 0.90 0.85, match:class ^(.+)$ # Regla general para todas las ventanas (transparencia base)

# Reglas especificas para kitty terminal
windowrule = no_blur on, opacity 0.85 0.85, match:class kitty 
# Reglas específicas para Dolphin
windowrule = no_blur on, opacity 0.99 0.99, match:class org.kde.dolphin
# Loupe visor de imágenes
# windowrule = float, match:class loupe
# windowrule = center, match:class loupe
# Editor de imágenes
windowrule = opacity 1.00 1.00, match:class darktable



# █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█


# Rofi
layerrule = match:namespace rofi, blur on
layerrule = match:namespace rofi, ignore_alpha 0

# Notifications & SwayNC
layerrule = match:namespace notifications, blur on
layerrule = match:namespace notifications, ignore_alpha 0
layerrule = match:namespace swaync-notification-window, blur on
layerrule = match:namespace swaync-notification-window, ignore_alpha 0
layerrule = match:namespace swaync-control-center, blur on
layerrule = match:namespace swaync-control-center, ignore_alpha 0

# Logout Dialog
layerrule = match:namespace logout_dialog, blur on